### ISSUE TITLE
Dark Mode Note Proper

### ISSUE THREAD

**Issue by POOPYFARTS-CODE** [Amazeryogo/Streamfish-Source-Code#7]
Dark Mode Is not properly set up u i have attached one file that will make ur site look more good (replace with ur dark mode css code)
link to code cant attach here (smh)
https://www.mediafire.com/file/2et9mgdzsgm2t6j/dark.css/file

**Comment by Amazeryogo** [comment]
make a pull request!

**Comment by Amazeryogo** [comment]
I have implemented some code but i also added some elements from Sreesanth, please look at the discussions, Thank you!
